package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "critical_values_cc_proto",
    deps = [":critical_values_proto"],
)

proto_library(
    name = "critical_values_proto",
    srcs = [":critical_values.proto"],
    deps = [],
)
