# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils/gui/wallet.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from utils.gui import identifier_pb2 as utils_dot_gui_dot_identifier__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16utils/gui/wallet.proto\x12\x06\x63ommon\x1a\x1autils/gui/identifier.proto\"\xb3\x01\n\x06Wallet\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0c\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04user\x18\x04 \x01(\t\x12\x15\n\ruser_password\x18\x05 \x01(\t\x12,\n\x07user_id\x18\x06 \x01(\x0b\x32\x1b.common.security.Identifier\x12\x0e\n\x06phrase\x18\x07 \x01(\t\x12\x15\n\rsub_addresses\x18\x08 \x03(\x0c\x42 \n\x11\x63om.keiros.commonB\x0bWalletClassb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.gui.wallet_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021com.keiros.commonB\013WalletClass'
  _globals['_WALLET']._serialized_start=63
  _globals['_WALLET']._serialized_end=242
# @@protoc_insertion_point(module_scope)
