package(default_visibility = ["//visibility:public"])

cc_library(
    name = "cryptonote_protocol",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.h"]) + glob(["*.inl"]),
    deps = ["//src/p2p"],
)
