cc_test(
    name = "libwallet_api_tests",
    srcs = ["main.cpp"],
    deps = [
        "//contrib/epee",
        "//src:version",
        "//src/device",
        "//src/wallet/api:wallet_api",
        "@boost//:chrono",
        "@boost//:filesystem",
        "@boost//:gtest",
        "@boost//:locale",
        "@boost//:serialization",
        "@boost//:system",
        "@boost//:thread",
    ],
)
