package(default_visibility = ["//visibility:public"])

cc_test(
    name = "transfers",
    srcs = ["transfers.cpp"],
    deps = [
        "//contrib/epee",
        "//src/common",
        "//src/crypto:cncrypto",
        "//src/cryptonote_core",
        "//src/rpc",
        "@gtest",
    ],
)
