
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "denarii-blockchain-export",
    hdrs = ["bootstrap_file.h", "blocksdat_file.h", "bootstrap_serialization.h"]
    srcs = ["blockchain_export.cpp", "bootstrap_file.cpp", "blocksdat_file.cpp"],
    deps = [],
)
