package(default_visibility = ["//visibility:public"])

cc_library(
    name = "multisig",
    srcs = ["multisig.cpp"],
    hdrs = ["multisig.h"],
    deps = [
        "//src/common",
        "//src/crypto:cncrypto",
        "//src/cryptonote_basic",
        "//src/ringct",
    ],
)
