package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "generate_translations",
    srcs = ["generate_translations_header.c"],
    deps = [],
)

cc_library(
    name = "translations",
    hdrs = ["translation_files.h"],
    deps = [],
)
