cc_test(
    name = "block_weight",
    srcs = ["block_weight.cpp"],
    deps = [
        "//src/blockchain_db",
        "//src/cryptonote_core",
    ],
)

py_test(
    name = "block_weight_py",
    srcs = [
        "block_weight.py",
        "compare.py",
    ],
    deps = [],
)
