package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "hash_tests_fast",
    srcs = ["main.cpp"],
    deps = [
        "//src:cncrypto",
        "//src:common",
        "//tests:io",
        "@liblzma",
    ],
)

cc_binary(
    name = "hash_tests_slow",
    srcs = ["main.cpp"],
    deps = [
        "//src:cncrypto",
        "//src:common",
        "//tests:io",
        "@liblzma",
    ],
)

cc_binary(
    name = "hash_tests_slow_1",
    srcs = ["main.cpp"],
    deps = [
        "//src:cncrypto",
        "//src:common",
        "//tests:io",
        "@liblzma",
    ],
)

cc_binary(
    name = "hash_tests_slow_2",
    srcs = ["main.cpp"],
    deps = [
        "//src:cncrypto",
        "//src:common",
        "//tests:io",
        "@liblzma",
    ],
)

cc_binary(
    name = "hash_tests_slow_3",
    srcs = ["main.cpp"],
    deps = [
        "//src:cncrypto",
        "//src:common",
        "//tests:io",
        "@liblzma",
    ],
)

cc_binary(
    name = "hash_tests_slow_4",
    srcs = ["main.cpp"],
    deps = [
        "//src:cncrypto",
        "//src:common",
        "//tests:io",
        "@liblzma",
    ],
)

cc_binary(
    name = "hash_tests_tree",
    srcs = ["main.cpp"],
    deps = [
        "//src:cncrypto",
        "//src:common",
        "//tests:io",
        "@liblzma",
    ],
)

cc_binary(
    name = "hash_tests_extra_blake",
    srcs = ["main.cpp"],
    deps = [
        "//src:cncrypto",
        "//src:common",
        "//tests:io",
        "@liblzma",
    ],
)

cc_binary(
    name = "hash_tests_extra_groestl",
    srcs = ["main.cpp"],
    deps = [
        "//src:cncrypto",
        "//src:common",
        "//tests:io",
        "@liblzma",
    ],
)

cc_binary(
    name = "hash_tests_extra_jh",
    srcs = ["main.cpp"],
    deps = [
        "//src:cncrypto",
        "//src:common",
        "//tests:io",
        "@liblzma",
    ],
)

cc_binary(
    name = "hash_tests_extra_skein",
    srcs = ["main.cpp"],
    deps = [
        "//src:cncrypto",
        "//src:common",
        "//tests:io",
        "@liblzma",
    ],
)

cc_binary(
    name = "hash_variant2_int_sqrt",
    srcs = ["main.cpp"],
    deps = [
        "//src:cncrypto",
        "//src:common",
        "//tests:io",
        "@liblzma",
    ],
)
