package(default_visibility = ["//visibility:public"])

cc_test(
    name = "hash_tests_fast",
    srcs = ["main.cpp"],
    copts = [
        "fast",
        "tests-fast.txt",
    ],
    deps = [
        "//src/common",
        "//src/crypto:cncrypto",
    ],
)

cc_test(
    name = "hash_tests_slow",
    srcs = ["main.cpp"],
    copts = [
        "slow",
        "tests-slow.txt",
    ],
    deps = [
        "//src/common",
        "//src/crypto:cncrypto",
    ],
)

cc_test(
    name = "hash_tests_slow_1",
    srcs = ["main.cpp"],
    copts = [
        "slow-1",
        "tests-slow-1.txt",
    ],
    deps = [
        "//src/common",
        "//src/crypto:cncrypto",
    ],
)

cc_test(
    name = "hash_tests_slow_2",
    srcs = ["main.cpp"],
    copts = [
        "slow-2",
        "tests-slow-2.txt",
    ],
    deps = [
        "//src/common",
        "//src/crypto:cncrypto",
    ],
)

cc_test(
    name = "hash_tests_slow_3",
    srcs = ["main.cpp"],
    copts = [
        "slow-3",
        "tests-slow-3.txt",
    ],
    deps = [
        "//src/common",
        "//src/crypto:cncrypto",
    ],
)

cc_test(
    name = "hash_tests_slow_4",
    srcs = ["main.cpp"],
    copts = [
        "slow-4",
        "tests-slow-4.txt",
    ],
    deps = [
        "//src/common",
        "//src/crypto:cncrypto",
    ],
)

cc_test(
    name = "hash_tests_tree",
    srcs = ["main.cpp"],
    copts = [
        "tree",
        "tests-tree.txt",
    ],
    deps = [
        "//src/common",
        "//src/crypto:cncrypto",
    ],
)

cc_test(
    name = "hash_tests_extra_blake",
    srcs = ["main.cpp"],
    copts = [
        "extra-blake",
        "tests-extra-blake.txt",
    ],
    deps = [
        "//src/common",
        "//src/crypto:cncrypto",
    ],
)

cc_test(
    name = "hash_tests_extra_groestl",
    srcs = ["main.cpp"],
    copts = [
        "extra-groestl",
        "tests-extra-groestl.txt",
    ],
    deps = [
        "//src/common",
        "//src/crypto:cncrypto",
    ],
)

cc_test(
    name = "hash_tests_extra_jh",
    srcs = ["main.cpp"],
    copts = [
        "extra-jh",
        "tests-extra-jh.txt",
    ],
    deps = [
        "//src/common",
        "//src/crypto:cncrypto",
    ],
)

cc_test(
    name = "hash_tests_extra_skein",
    srcs = ["main.cpp"],
    copts = [
        "extra-skein",
        "tests-extra-skein.txt",
    ],
    deps = [
        "//src/common",
        "//src/crypto:cncrypto",
    ],
)

cc_test(
    name = "hash_variant2_int_sqrt",
    srcs = ["main.cpp"],
    copts = ["variant2_int_sqrt"],
    deps = [
        "//src/common",
        "//src/crypto:cncrypto",
    ],
)
