package(default_visibility = ["//visibility:public"])

cc_test(
    name = "core_proxy",
    srcs = [
        "core_proxy.cpp",
        "core_proxy.h",
    ],
    deps = [
        "//contrib/epee",
        "//src:version",
        "//src/cryptonote_core",
        "//src/cryptonote_protocol",
        "//src/p2p",
    ],
)
