package(default_visibility = ["//visibility:public"])

py_binary(
  name = "console",
  srcs = ["console.py"],
  deps = [framework:daemon", "framework:wallet"],
  imports = [framework:daemon", "framework:wallet"],
)