
#define DEF_MONERO_VERSION_TAG "5b27ac195"

#define DEF_MONERO_VERSION "0.17.1.5"

#define DEF_MONERO_RELEASE_NAME "Oxygen Orion"

#define DEF_MONERO_VERSION_FULL DEF_MONERO_VERSION "-" DEF_MONERO_VERSION_TAG

#define DEF_MONERO_VERSION_IS_RELEASE false



#include "version.h"



const char* const MONERO_VERSION_TAG = DEF_MONERO_VERSION_TAG;

const char* const MONERO_VERSION = DEF_MONERO_VERSION;

const char* const MONERO_RELEASE_NAME = DEF_MONERO_RELEASE_NAME;

const char* const MONERO_VERSION_FULL = DEF_MONERO_VERSION_FULL;

const bool MONERO_VERSION_IS_RELEASE = DEF_MONERO_VERSION_IS_RELEASE;

