package(default_visibility = ["//visibility:public"])

cc_library(
    name = "wallet_crypto",
    srcs = [],
    hdrs = [
        "crypto.h",
        "ops.h",
    ],
    deps = [
        "//src:cncrypto",
        "@supercop//:supercop51",
        "@supercop//:supercop64",
    ],
)
