name: bazel_ubuntu
permissions: read-all

on: [push, pull_request]

jobs:
  build-ubuntu:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive
          update: true
          install: sudo apt update && sudo apt install build-essential cmake pkg-config libboost-all-dev libssl-dev libzmq3-dev libunbound-dev libsodium-dev libunwind8-dev liblzma-dev libreadline6-dev libldns-dev libexpat1-dev doxygen graphviz libpgm-dev qttools5-dev-tools libhidapi-dev libusb-1.0-0-dev libprotobuf-dev protobuf-compiler libudev-dev libnorm-dev  qtbase5-dev qt5-qmake python-pip && sudo apt-get install python3-pyqt5
      - run: bazelisk build src:all --@boost.asio//:ssl=openssl
      - run: bazelisk build utils/gui
      - run: bazelisk run tests:run_monero_tests  --@boost.asio//:ssl=openssl
      - run: bazelisk run tests/core_tests  --@boost.asio//:ssl=openssl -- --generate_and_play_test_data
      - run: bazelisk run tests/functional_tests:functional_tests_rpc  --@boost.asio//:ssl=openssl -- -- python3 ${GITHUB_WORKSPACE}/tests/functional_tests ${GITHUB_WORKSPACE}/bazel-bin all
      - run: bazelisk run tests/functional_tests:check_missing_rpc_methods  --@boost.asio//:ssl=openssl -- ${GITHUB_WORKSPACE}/tests/functional_tests
      - run: bazelisk test utils/gui:all
