name: bazel

on: [push, pull_request]

jobs:
  build-ubuntu:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@main
      with:
        submodules: recursive
        update: true
        install: sudo apt update && sudo apt install build-essential cmake pkg-config libboost-all-dev libssl-dev libzmq3-dev libunbound-dev libsodium-dev libunwind8-dev liblzma-dev libreadline6-dev libldns-dev libexpat1-dev doxygen graphviz libpgm-dev qttools5-dev-tools libhidapi-dev libusb-1.0-0-dev libprotobuf-dev protobuf-compiler libudev-dev libnorm-dev  qtbase5-dev qt5-qmake python-pip && sudo apt-get install python3-pyqt5
    - run: bazelisk build src:all --@boost.asio//:ssl=openssl
    - run: bazelisk build utils/gui
    - run: bazelisk run tests/core_tests  --@boost.asio//:ssl=openssl -- --generate_and_play_test_data
    - run: bazelisk run tests/functional_tests:functional_tests_rpc  --@boost.asio//:ssl=openssl -- -- python3 ${GITHUB_WORKSPACE}/tests/functional_tests ${GITHUB_WORKSPACE}/bazel-bin all
    - run: bazelisk run tests/functional_tests:check_missing_rpc_methods  --@boost.asio//:ssl=openssl -- ${GITHUB_WORKSPACE}/tests/functional_tests
    - run: bazelisk test utils/gui:all
  build-macos:
    strategy:
      matrix:
        os:
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@main
      with:
        submodules: recursive
        update: true
        install: brew update && brew bundle --file=contrib/brew/Brewfile && pip3 install PyQt5
    - run: bazelisk build src:all --@boost.asio//:ssl=openssl
    - run: bazelisk build utils/gui
    - run: bazelisk run tests/core_tests  --@boost.asio//:ssl=openssl -- --generate_and_play_test_data
    - run: bazelisk run tests/functional_tests:functional_tests_rpc  --@boost.asio//:ssl=openssl -- -- python3 ${GITHUB_WORKSPACE}/tests/functional_tests ${GITHUB_WORKSPACE}/bazel-bin all
    - run: bazelisk run tests/functional_tests:check_missing_rpc_methods  --@boost.asio//:ssl=openssl -- ${GITHUB_WORKSPACE}/tests/functional_tests
    - run: bazelisk test utils/gui:all
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@main
      with:
        submodules: recursive
    - uses: eine/setup-msys2@v1
      with:
        update: true
        install: mingw-w64-x86_64-toolchain make mingw-w64-x86_64-cmake mingw-w64-x86_64-boost mingw-w64-x86_64-openssl mingw-w64-x86_64-zeromq mingw-w64-x86_64-libsodium mingw-w64-x86_64-hidapi mingw-w64-x86_64-libunwind mingw-w64-x86_64-libusb mingw-w64-x86_64-unbound mingw-w64-x86_64-lmdb mingw-w64-x86_64-qt-creator mingw-w64-x86_64-python-pyqt5 mingw-w64-x86_64-qt5-tools
    - run: bazelisk --output_base="C:\bazel-bin" build  --extra_toolchains=@local_config_cc//:cc-toolchain-x64_windows_mingw --extra_execution_platforms=//:windows-mingw-gcc src:all --compiler=mingw-gcc --host_compiler=mingmw-gcc --copt="-O3" --copt="-DWIN32_LEAN_AND_MEAN" --copt="-DMINIUPNP_STATICLIB" --copt="-DZMQ_STATIC" --linkopt="-static" --@boost.asio//:ssl=openssl
    - run: bazelisk build utils/gui
    - run: bazelisk --output_base="C:\bazel-bin" run  --extra_toolchains=@local_config_cc//:cc-toolchain-x64_windows_mingw --extra_execution_platforms=//:windows-mingw-gcc tests/core_tests --compiler=mingw-gcc --host_compiler=mingmw-gcc --copt="-O3" --copt="-DWIN32_LEAN_AND_MEAN" --copt="-DMINIUPNP_STATICLIB" --copt="-DZMQ_STATIC" --linkopt="-static" -- --generate_and_play_test_data
    - run: bazelisk --output_base="C:\bazel-bin" run  --extra_toolchains=@local_config_cc//:cc-toolchain-x64_windows_mingw --extra_execution_platforms=//:windows-mingw-gcc tests/functional_tests:functional_tests_rpc --compiler=mingw-gcc --host_compiler=mingmw-gcc --copt="-O3" --copt="-DWIN32_LEAN_AND_MEAN" --copt="-DMINIUPNP_STATICLIB" --copt="-DZMQ_STATIC" --linkopt="-static" -- python3 ${GITHUB_WORKSPACE}/tests/functional_tests ${GITHUB_WORKSPACE}/bazel-bin all
    - run: bazelisk --output_base="C:\bazel-bin" run  --extra_toolchains=@local_config_cc//:cc-toolchain-x64_windows_mingw --extra_execution_platforms=//:windows-mingw-gcc tests/functional_tests:check_missing_rpc_methods --compiler=mingw-gcc --host_compiler=mingmw-gcc --copt="-O3" --copt="-DWIN32_LEAN_AND_MEAN" --copt="-DMINIUPNP_STATICLIB" --copt="-DZMQ_STATIC" --linkopt="-static" --  ${GITHUB_WORKSPACE}/tests/functional_tests
    - run: bazelisk test utils/gui:all